name: demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7

    - name: Build with Maven
      run: mvn clean install

    - name: Test with JUnit
      run: mvn test
      
    - name: Test report output
      run: mvn clean \
                install \
                test -Dmaven.test.failure.ignore=true \
                site -DgenerateReports=false \
                surefire-report:report